### ISSUE TITLE
Add sys/app entries

### ISSUE THREAD

**Issue by quantumproducer** [hcs42/cowboy_tutorial_webchat#3]
5. Add cowboy apps to reltool.config

Edit rel/reltool.config: add the crypto, mimetypes, ranch and cowboy applications to sys/rel and add them as sys/app entries.

I don't see a sys/app. What's the file supposed to look like?

**Comment by hcs42** [comment]
This repository contains each step of the tutorial as a commit: https://github.com/hcs42/cowboy_tutorial_webchat/commits/master For example this is the step that you are asking about:
https://github.com/hcs42/cowboy_tutorial_webchat/commit/a2ad007ebcdb6f1dd3bddb213d69614d6add6992#diff-ee46c4f44a5bbed6a202d50607d65ac5

Note tough that this tutorial uses an old version of cowboy, an old version of rebar, and an old version of Erlang. Further steps will probably not work so I recommend not using this tutorial. I have updated the README to reflect this.
